#æ–‡ç« é…ç½®
post:
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png
  default_index_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/posts/default.webp
  #è¯„è®º
  comments: 
    enable: true
    type: utterances
utterances:
  repo: qiongxing/qiongxing.github.commit
  issue-term: "title"
  label: "âœ¨ğŸ’¬âœ¨"
  theme: "github-light"
  crossorigin: "anonymous"

#å½’æ¡£
archive:
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png

#æ ‡ç­¾
tag:
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png
#åˆ†ç±»
category:
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png

fun_features:
  typing: # ä¸º subtitle æ·»åŠ æ‰“å­—æœºæ•ˆæœ
    enable: true
    typeSpeed: 70 # æ‰“å°é€Ÿåº¦
    cursorChar: "ğŸ‹" # æ¸¸æ ‡å­—ç¬¦
    loop: false # æ˜¯å¦å¾ªç¯æ’­æ”¾æ•ˆæœ

index:
  #é¡¶éƒ¨å›¾ç‰‡
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png
  slogan:
    enable: true
    text: "ä¸ºå­¦æ—¥ç›Šï¼Œä¸ºé“æ—¥æŸã€‚æŸä¹‹åˆæŸï¼Œä»¥è‡³äºæ— ä¸ºã€‚"

navbar:
  blog_title: QiongXingä¸è¯†

#å¼ºåˆ¶å¼€å¯https
force_https: true

favicon: /img/medium32x32.ico

#ä»£ç å—é…ç½®
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "prismjs"
    highlightjs:
      style: "Github Gist"
      bg_color: true
    prismjs:
      style: "default"
      preprocess: true

#å…³äº
about:
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png
  avatar: /img/avatar.jpg
  name: "QiongXing"
  intro: "åšæŒæ¯å¤©å­¦ä¹ ï¼Œé”»ç‚¼çš„èœé¸Ÿ"
  icons:
    - {
        class: "iconfont icon-github-fill",
        link: "https://github.com/qiongxing",
        tip: "GitHub",
      }
    # - {
    #     class: "iconfont icon-douban-fill",
    #     link: "https://douban.com",
    #     tip: "è±†ç“£",
    #   }
    - { class: "iconfont icon-qq-fill", qrcode: "/img/qq.png" }

page404:
  enable: true
  banner_img: https://cdn.jsdelivr.net/gh/qiongxing/qiongxing.github.io@main/source/img/home.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  subtitle: "æ²¡æœ‰å½“å‰æ–‡ç« ğŸ˜­"

footer:
  content: "
    <span>å¥¥ç‰¹æ›¼ä¿æŠ¤å°æ€ªå…½</span>
    "
  statistics:
    enable: true
    source: "busuanzi" # å¯é€‰ leancloud | busuanzi  æ ¹æ®è‡ªå·±éœ€æ±‚é€‰æ‹©
    pv_format: "æ€»è®¿é—®é‡ {} æ¬¡" # æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{}æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
    uv_format: "æ€»è®¿å®¢æ•° {} äºº"


# static_prefix:
#   highlightjs: https://cdn.jsdelivr.net/npm/highlight.js@10.6.0/